sudo: required
services:
  - docker

before_install:
  - docker build -t solareenlo/frontend-docker-react -f Dockerfile.dev .

script:
  - docker run solareenlo/frontend-docker-react npm run test -- --coverage
