sudo: required
services:
  - docker

before_install:
  - docker build -t solareenlo/frontend-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true solareenlo/frontend-docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-docker-react"
  env: "FrontendDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-998768475306"
  bucket_path: "frontend-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
